import type { Locale } from "@/lib/bluewolf-data";

export const authCopy = {
    ko: {
        logout: "로그아웃",
        loginTitle: "로그인",
        loginDesc: "아이디와 비밀번호를 입력하고 BlueWolf 여행을 이어가보세요.",
        loginButton: "로그인",
        signupTitle: "회원가입",
        signupDesc: "새 계정을 만들고 여행 계획을 저장해보세요.",
        signupButton: "회원가입",
        forgotTitle: "비밀번호 찾기",
        forgotDesc: "아이디를 입력하면 등록된 이메일로 인증코드를 보내드립니다. 인증을 마친 뒤 새 비밀번호를 설정할 수 있어요.",
        forgotButton: "비밀번호 재설정",
        forgotStep1Title: "1. 아이디 확인",
        forgotStep1Desc: "비밀번호를 재설정할 계정의 아이디를 입력해주세요.",
        forgotStep2Title: "2. 이메일 인증",
        forgotStep2Desc: "{email} 으로 6자리 인증코드를 보냈습니다. 10분 안에 입력해주세요.",
        forgotStep3Title: "3. 새 비밀번호 설정",
        forgotStep3Desc: "인증이 완료되었습니다. 새 비밀번호를 입력해주세요.",
        forgotSendCodeBtn: "인증코드 받기",
        forgotResendCodeBtn: "다시 보내기",
        forgotChangeIdBtn: "아이디 다시 입력",
        forgotEmailNotRegistered: "이 아이디에는 이메일이 등록되어 있지 않습니다. 고객센터에 문의해주세요.",
        userIdLabel: "아이디",
        nameLabel: "이름",
        phoneLabel: "전화번호",
        emailLabel: "이메일",
        verificationCodeLabel: "인증코드",
        verificationCodePlaceholder: "6자리 인증코드",
        sendVerificationCode: "인증코드 보내기",
        resendVerificationCode: "인증코드 다시 보내기",
        sendingVerificationCode: "전송 중...",
        verifyVerificationCode: "인증하기",
        verifyingVerificationCode: "확인 중...",
        verificationCodeSent: "입력한 이메일로 인증코드를 보냈습니다.",
        emailVerified: "이메일 인증이 완료되었습니다.",
        emailVerifiedShort: "인증 완료",
        passwordLabel: "비밀번호",
        confirmPasswordLabel: "비밀번호 확인",
        passwordHint: "6자 이상 입력해주세요.",
        home: "홈으로 돌아가기",
        loggedIn: "이미 로그인되어 있습니다.",
        continue: "계속 둘러보기",
        needAccount: "계정이 없으신가요?",
        goSignup: "회원가입",
        goLogin: "로그인으로 돌아가기",
        forgotPassword: "비밀번호 찾기",
        haveAccount: "이미 계정이 있으신가요?",
        resetDone: "비밀번호가 재설정되었습니다. 새 비밀번호로 로그인해보세요.",
        signupDone: "회원가입이 완료되었습니다. 바로 로그인해보세요.",
        requiredUserId: "아이디를 입력해주세요.",
        invalidUserId: "아이디는 4자 이상이어야 합니다.",
        requiredName: "이름을 입력해주세요.",
        requiredPhone: "전화번호를 입력해주세요.",
        requiredEmail: "이메일을 입력해주세요.",
        invalidEmail: "올바른 이메일 형식이 아닙니다.",
        emailVerificationRequired: "이메일 인증을 완료해주세요.",
        requiredVerificationCode: "인증코드를 입력해주세요.",
        invalidVerificationCode: "인증코드가 올바르지 않거나 만료되었습니다.",
        requiredPassword: "비밀번호를 입력해주세요.",
        invalidPassword: "비밀번호는 6자 이상이어야 합니다.",
        passwordMismatch: "비밀번호가 서로 일치하지 않습니다.",
        loginFailed: "아이디 또는 비밀번호가 올바르지 않습니다.",
        accountLocked: "로그인 실패가 반복되어 계정이 잠시 잠겼습니다. 잠시 후 다시 시도해주세요.",
        requestLimited: "요청이 너무 많습니다. 잠시 후 다시 시도해주세요.",
        userExists: "이미 사용 중인 아이디입니다.",
        userNotFound: "해당 아이디를 찾을 수 없습니다.",
        systemError: "잠시 후 다시 시도해주세요.",
    },
    ja: {
        logout: "ログアウト",
        loginTitle: "ログイン",
        loginDesc: "IDとパスワードを入力して BlueWolf の旅を続けましょう。",
        loginButton: "ログイン",
        signupTitle: "会員登録",
        signupDesc: "新しいアカウントを作成して旅行プランを保存しましょう。",
        signupButton: "会員登録",
        forgotTitle: "パスワード再設定",
        forgotDesc: "IDを入力すると、登録メールアドレス宛に認証コードを送信します。認証完了後に新しいパスワードを設定できます。",
        forgotButton: "パスワード再設定",
        forgotStep1Title: "1. IDの確認",
        forgotStep1Desc: "パスワードを再設定するアカウントの ID を入力してください。",
        forgotStep2Title: "2. メール認証",
        forgotStep2Desc: "{email} に6桁の認証コードを送信しました。10分以内に入力してください。",
        forgotStep3Title: "3. 新しいパスワードの設定",
        forgotStep3Desc: "認証が完了しました。新しいパスワードを入力してください。",
        forgotSendCodeBtn: "認証コード送信",
        forgotResendCodeBtn: "再送信",
        forgotChangeIdBtn: "IDを入力し直す",
        forgotEmailNotRegistered: "この ID にはメールアドレスが登録されていません。カスタマーサポートまでお問い合わせください。",
        userIdLabel: "ID",
        nameLabel: "お名前",
        phoneLabel: "電話番号",
        emailLabel: "メールアドレス",
        verificationCodeLabel: "認証コード",
        verificationCodePlaceholder: "6桁の認証コード",
        sendVerificationCode: "認証コード送信",
        resendVerificationCode: "認証コード再送信",
        sendingVerificationCode: "送信中...",
        verifyVerificationCode: "認証する",
        verifyingVerificationCode: "確認中...",
        verificationCodeSent: "入力したメールアドレスに認証コードを送信しました。",
        emailVerified: "メール認証が完了しました。",
        emailVerifiedShort: "認証完了",
        passwordLabel: "パスワード",
        confirmPasswordLabel: "パスワード確認",
        passwordHint: "6文字以上入力してください。",
        home: "ホームへ戻る",
        loggedIn: "すでにログインしています。",
        continue: "続けて見る",
        needAccount: "アカウントをお持ちではありませんか？",
        goSignup: "会員登録",
        goLogin: "ログインへ戻る",
        forgotPassword: "パスワードを忘れた方",
        haveAccount: "すでにアカウントをお持ちですか？",
        resetDone: "パスワードが再設定されました。新しいパスワードでログインしてください。",
        signupDone: "会員登録が完了しました。すぐにログインできます。",
        requiredUserId: "IDを入力してください。",
        invalidUserId: "IDは4文字以上で入力してください。",
        requiredName: "お名前を入力してください。",
        requiredPhone: "電話番号を入力してください。",
        requiredEmail: "メールアドレスを入力してください。",
        invalidEmail: "メールアドレスの形式が正しくありません。",
        emailVerificationRequired: "メール認証を完了してください。",
        requiredVerificationCode: "認証コードを入力してください。",
        invalidVerificationCode: "認証コードが正しくないか、有効期限が切れています。",
        requiredPassword: "パスワードを入力してください。",
        invalidPassword: "パスワードは6文字以上で入力してください。",
        passwordMismatch: "パスワードが一致しません。",
        loginFailed: "IDまたはパスワードが正しくありません。",
        accountLocked: "ログイン失敗が続いたため、アカウントを一時的にロックしました。しばらくしてからもう一度お試しください。",
        requestLimited: "リクエストが多すぎます。しばらくしてからもう一度お試しください。",
        userExists: "この ID はすでに使用されています。",
        userNotFound: "該当する ID が見つかりません。",
        systemError: "しばらくしてからもう一度お試しください。",
    },
    en: {
        logout: "Log out",
        loginTitle: "Log in",
        loginDesc: "Enter your ID and password to continue your BlueWolf journey.",
        loginButton: "Log in",
        signupTitle: "Sign up",
        signupDesc: "Create a new account and save your travel plans.",
        signupButton: "Sign up",
        forgotTitle: "Reset password",
        forgotDesc: "Enter your user ID and we'll email a verification code to your registered address. After verifying, you can choose a new password.",
        forgotButton: "Reset password",
        forgotStep1Title: "1. Confirm your ID",
        forgotStep1Desc: "Enter the user ID of the account you want to reset.",
        forgotStep2Title: "2. Verify your email",
        forgotStep2Desc: "We sent a 6-digit code to {email}. Enter it within 10 minutes.",
        forgotStep3Title: "3. Choose a new password",
        forgotStep3Desc: "Verification complete. Set your new password below.",
        forgotSendCodeBtn: "Send verification code",
        forgotResendCodeBtn: "Resend code",
        forgotChangeIdBtn: "Use a different ID",
        forgotEmailNotRegistered: "There's no email on file for this ID. Please contact customer support.",
        userIdLabel: "User ID",
        nameLabel: "Full name",
        phoneLabel: "Phone number",
        emailLabel: "Email",
        verificationCodeLabel: "Verification code",
        verificationCodePlaceholder: "6-digit verification code",
        sendVerificationCode: "Send code",
        resendVerificationCode: "Resend code",
        sendingVerificationCode: "Sending...",
        verifyVerificationCode: "Verify",
        verifyingVerificationCode: "Verifying...",
        verificationCodeSent: "A verification code has been sent to your email.",
        emailVerified: "Your email has been verified.",
        emailVerifiedShort: "Verified",
        passwordLabel: "Password",
        confirmPasswordLabel: "Confirm password",
        passwordHint: "Use at least 6 characters.",
        home: "Back to home",
        loggedIn: "You are already signed in.",
        continue: "Keep exploring",
        needAccount: "Don't have an account?",
        goSignup: "Sign up",
        goLogin: "Back to log in",
        forgotPassword: "Forgot password",
        haveAccount: "Already have an account?",
        resetDone: "Your password has been reset. Try logging in again.",
        signupDone: "Your account has been created. You can log in now.",
        requiredUserId: "Please enter your user ID.",
        invalidUserId: "User ID must be at least 4 characters.",
        requiredName: "Please enter your name.",
        requiredPhone: "Please enter your phone number.",
        requiredEmail: "Please enter your email.",
        invalidEmail: "Please enter a valid email address.",
        emailVerificationRequired: "Please complete email verification.",
        requiredVerificationCode: "Please enter the verification code.",
        invalidVerificationCode: "The verification code is invalid or expired.",
        requiredPassword: "Please enter your password.",
        invalidPassword: "Password must be at least 6 characters.",
        passwordMismatch: "Passwords do not match.",
        loginFailed: "Your ID or password is incorrect.",
        accountLocked: "Too many failed login attempts. This account is temporarily locked.",
        requestLimited: "Too many requests. Please try again later.",
        userExists: "This ID is already in use.",
        userNotFound: "We could not find that ID.",
        systemError: "Please try again in a moment.",
    },
} as const satisfies Record<Locale, Record<string, string>>;
