export const copy = {
    ko: {
        brand: "BlueWolf",
        navPlans: "투어상품",
        navApplication: "신청",
        navCommunity: "커뮤니티",
        navFaq: "FAQ",
        login: "로그인",
        heroBadge: "몽골 여행, 더 쉽고 더 세련되게",
        heroTitle: "BlueWolf와 함께\n몽골 여행을 가장 편하게 예약하세요",
        heroDesc:
            "실제 운영을 고려한 몽골 여행 플랫폼. 상품 탐색, 예약, 결제, 후기, 동행 구하기까지 한 번에 연결되는 구조입니다.",
        heroPrimary: "여행 상품 보기",
        heroSecondary: "플랜 상담 시작",
        searchPlaceholder: "상품명 또는 키워드 검색",
        allDuration: "전체 일정",
        shortDuration: "3~4일",
        longDuration: "5일 이상",
        allDurationShort: "4박 이하",
        allDurationLong: "5박 이상",
        allRegion: "전체 지역",
        gobi: "고비",
        south: "남부",
        central: "중부",
        north: "북부",
        west: "서부",
        allTheme: "전체 테마",
        desert: "사막",
        family: "가족",
        premium: "프리미엄",
        adventure: "어드벤처",
        popularSort: "인기순",
        lowSort: "낮은 가격순",
        highSort: "높은 가격순",
        featured: "추천 여행 상품",
        featuredDesc: "실제 판매용을 염두에 둔 검색/필터/상세 흐름입니다.",
        reset: "필터 초기화",
        details: "상세보기",
        reserve: "플랜 신청하기",
        applicationTitle: "플랜 상담/신청",
        applicationDesc: "출발 희망일과 인원 정보를 입력하면 예상 금액이 자동 계산됩니다.",
        selectPlan: "상품 선택",
        departDate: "출발 희망일",
        guests: "인원 수",
        name: "신청자 이름",
        phone: "연락처",
        memo: "요청사항",
        payPlanPackageFee: "플랜 패키지 결제 진행",
        getQuote: "견적서 받기",
        communityTitle: "동행 · 후기 커뮤니티",
        faqTitle: "자주 묻는 질문",
        footer: "몽골 전문 여행 플랫폼 · 한국어 / 일본어 / 영어 지원",
        dashboard1: "이번 달 방문자",
        dashboard2: "신청 전환율",
        dashboard3: "평균 객단가",
        dashboard4: "리뷰 평점",
        priceLabel: "1인 기준",
        selectedPlan: "선택 상품",
        totalPrice: "예상 총액",
        planPackageFee: "플랜 패키지 이용료",
        guestsLabel: "인원 수",
        noResults: "검색 결과가 없습니다.",
        noResultsDesc: "다른 조건으로 다시 검색해보세요.",
        tabAll: "전체",
        tabReview: "후기",
        tabMate: "동행",
        tabQna: "질문",
        payReady: "아직 결제가 진행되지 않았습니다.",
        payDone: "플랜 패키지 결제가 완료되었습니다. 운영자 확인 후 안내가 발송됩니다.",
        featuredLabel: "이벤트",
        pausedLabel: "일시정지",
        delete: "삭제",
        today: "오늘",
        weekdays: ["일", "월", "화", "수", "목", "금", "토"] as const,
        datePlaceholder: "연도-월-일",
        publishPhase1: "1단계 · MVP 공개",
        publishPhase2: "2단계 · 운영 기능 연결",
        publishPhase3: "3단계 · 실서비스 확장",
        publishDesc1: "정적 랜딩, 상품 탐색, 플랜 신청 접수 중심으로 빠르게 오픈",
        publishDesc2: "결제, 관리자, 문의 흐름을 연결해 실제 운영 전환",
        publishDesc3: "커뮤니티, 후기, 다국어 SEO, 분석 고도화 적용",
    },
    ja: {
        brand: "BlueWolf",
        navPlans: "ツアー商品",
        navApplication: "申請",
        navCommunity: "コミュニティ",
        navFaq: "FAQ",
        login: "ログイン",
        heroBadge: "モンゴル旅行をもっと簡単に、もっと洗練して",
        heroTitle: "BlueWolfでモンゴル旅行をもっと手軽に予約",
        heroDesc:
            "実運用を意識したモンゴル旅行プラットフォーム。商品検索、予約、決済、レビュー、同行募集まで一つの流れでつながります。",
        heroPrimary: "商品を見る",
        heroSecondary: "予約相談を始める",
        searchPlaceholder: "商品名またはキーワード検索",
        allDuration: "全日程",
        shortDuration: "3〜4日",
        longDuration: "5日以上",
        allDurationShort: "4泊以下",
        allDurationLong: "5泊以上",
        allRegion: "全地域",
        gobi: "ゴビ",
        south: "南部",
        central: "中央",
        north: "北部",
        west: "西部",
        allTheme: "全テーマ",
        desert: "砂漠",
        family: "家族",
        premium: "プレミアム",
        adventure: "アドベンチャー",
        popularSort: "人気順",
        lowSort: "低価格順",
        highSort: "高価格順",
        featured: "おすすめツアー",
        featuredDesc: "実販売を想定した検索/フィルター/詳細導線です。",
        reset: "フィルター初期化",
        details: "詳細を見る",
        reserve: "プラン申請する",
        applicationTitle: "プラン相談/申請",
        applicationDesc: "出発希望日と人数を入力すると概算金額が自動計算されます。",
        selectPlan: "商品選択",
        departDate: "出発希望日",
        guests: "人数",
        name: "申請者名",
        phone: "連絡先",
        memo: "リクエスト",
        payPlanPackageFee: "プランパッケージ利用料を支払う",
        getQuote: "見積書を受け取る",
        communityTitle: "同行・レビューコミュニティ",
        faqTitle: "よくある質問",
        footer: "モンゴル専門旅行プラットフォーム · 韓国語 / 日本語 / 英語対応",
        dashboard1: "今月の訪問者",
        dashboard2: "申請転換率",
        dashboard3: "平均客単価",
        dashboard4: "レビュー評価",
        priceLabel: "1名料金",
        selectedPlan: "選択商品",
        totalPrice: "概算総額",
        planPackageFee: "プランパッケージ利用料",
        guestsLabel: "人数",
        noResults: "検索結果がありません。",
        noResultsDesc: "条件を変えて再検索してください。",
        tabAll: "すべて",
        tabReview: "レビュー",
        tabMate: "同行",
        tabQna: "質問",
        payReady: "まだ決済は開始されていません。",
        payDone: "プランパッケージ決済が完了しました。確認後に案内が送信されます。",
        featuredLabel: "イベント",
        pausedLabel: "一時停止",
        delete: "削除",
        today: "今日",
        weekdays: ["日", "月", "火", "水", "木", "金", "土"] as const,
        datePlaceholder: "年-月-日",
        publishPhase1: "第1段階 · MVP公開",
        publishPhase2: "第2段階 · 運用機能接続",
        publishPhase3: "第3段階 · 本番拡張",
        publishDesc1: "静的ランディングと商品閲覧、プラン申請受付中心で素早く公開",
        publishDesc2: "決済、管理、問い合わせ導線をつなぎ実運用に移行",
        publishDesc3: "コミュニティ、レビュー、多言語SEO、分析を高度化",
    },
    en: {
        brand: "BlueWolf",
        navPlans: "Plans",
        navApplication: "Apply",
        navCommunity: "Community",
        navFaq: "FAQ",
        login: "Log in",
        heroBadge: "Mongolia travel, simpler and smarter",
        heroTitle: "Apply your Mongolia trip with BlueWolf the easy way",
        heroDesc:
            "An operations-ready Mongolia travel platform connecting product discovery, plan application, payment, reviews, and traveler community in one flow.",
        heroPrimary: "View plans",
        heroSecondary: "Start application",
        searchPlaceholder: "Search by plan name or keyword",
        allDuration: "All durations",
        shortDuration: "3–4 days",
        longDuration: "5+ days",
        allDurationShort: "Up to 4 nights",
        allDurationLong: "5+ nights",
        allRegion: "All regions",
        gobi: "Gobi",
        south: "South",
        central: "Central",
        north: "North",
        west: "West",
        allTheme: "All themes",
        desert: "Desert",
        family: "Family",
        premium: "Premium",
        adventure: "Adventure",
        popularSort: "Most popular",
        lowSort: "Price: low to high",
        highSort: "Price: high to low",
        featured: "Featured plans",
        featuredDesc: "Search, filter, and detail flows designed for real conversion.",
        reset: "Reset filters",
        details: "View details",
        reserve: "Apply for this plan",
        applicationTitle: "Plan inquiry / application",
        applicationDesc: "Enter your preferred departure date and guest count to calculate the estimate automatically.",
        selectPlan: "Select plan",
        departDate: "Preferred date",
        guests: "Guests",
        name: "Applicant name",
        phone: "Phone number",
        memo: "Request details",
        payPlanPackageFee: "Pay plan package fee",
        getQuote: "Get quote",
        communityTitle: "Traveler community",
        faqTitle: "Frequently asked questions",
        footer: "Mongolia travel platform · Korean / Japanese / English",
        dashboard1: "Monthly visitors",
        dashboard2: "Application conversion",
        dashboard3: "Average order value",
        dashboard4: "Review score",
        priceLabel: "Per person",
        selectedPlan: "Selected plan",
        totalPrice: "Estimated total",
        planPackageFee: "Plan package fee",
        guestsLabel: "Guests",
        noResults: "No plans matched your filters.",
        noResultsDesc: "Try adjusting your search or filters.",
        tabAll: "All",
        tabReview: "Reviews",
        tabMate: "Companions",
        tabQna: "Questions",
        payReady: "No payment has started yet.",
        payDone: "Plan package fee payment completed. A confirmation notice will be sent after review.",
        featuredLabel: "Event",
        pausedLabel: "Paused",
        delete: "Clear",
        today: "Today",
        weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"] as const,
        datePlaceholder: "YYYY-MM-DD",
        publishPhase1: "Phase 1 · MVP Launch",
        publishPhase2: "Phase 2 · Ops Integration",
        publishPhase3: "Phase 3 · Scale Up",
        publishDesc1: "Launch quickly with landing, catalog, and application request flow.",
        publishDesc2: "Connect payment, admin, and inquiry workflow for live operations.",
        publishDesc3: "Expand community, reviews, multilingual SEO, and analytics.",
    },
} as const;
