import { normalizeCmsTourImages } from "@/lib/cms-image";
import { type Tour } from "@/lib/bluewolf-types";

export const tours: Tour[] = ([
    {
        id: 1,
        region: "south",
        theme: "desert",
        durationType: "long",
        price: 1690000,
        deposit: 50000,
        gradient: "from-blue-600 to-blue-400",
        heroImage: "/images/tour-gobi-5n6d.jpg",
        images: ["/images/hero-gobi.jpg", "/images/tour-gobi-4n5d.jpg", "/images/tour-gobi-6n7d.jpg"],
        detailImages: ["/images/detail-sample.jpg"],
        title: { ko: "고비 사막 5박 6일", ja: "ゴビ砂漠 5泊6日", en: "Gobi Desert 5N6D" },
        desc: {
            ko: "가장 인기 있는 대표 코스. 사막, 협곡, 별보기, 게르 숙박까지 한 번에 즐깁니다.",
            ja: "砂漠・峡谷・星空観察・ゲル宿泊まで楽しめる人気コースです。",
            en: "Our signature route covering desert, canyon, stargazing, and ger stay.",
        },
        tags: {
            ko: ["베스트", "별보기", "한국어 가이드"],
            ja: ["人気", "星空", "韓国語ガイド"],
            en: ["Best", "Stargazing", "Korean Guide"],
        },
        duration: { ko: "5박 6일", ja: "5泊6日", en: "5 nights 6 days" },
        highlights: {
            ko: ["고비 사막", "별보기", "게르 숙박", "협곡 투어"],
            ja: ["ゴビ砂漠", "星空観察", "ゲル宿泊", "渓谷ツアー"],
            en: ["Gobi Desert", "Stargazing", "Ger Stay", "Canyon Tour"],
        },
    },
    {
        id: 2,
        region: "central",
        theme: "family",
        durationType: "short",
        price: 990000,
        deposit: 50000,
        gradient: "from-sky-900 to-blue-500",
        heroImage: "/images/tour-steppe-3n4d.jpg",
        images: ["/images/hero-terelj.jpg", "/images/tour-steppe-2n3d.jpg", "/images/tour-steppe-4n5d.jpg"],
        detailImages: ["/images/detail-sample.jpg"],
        title: { ko: "테를지 · 미니사막 3박 4일", ja: "テレルジ・ミニ砂漠 3泊4日", en: "Terelj & Mini Desert 3N4D" },
        desc: {
            ko: "짧은 일정으로 몽골의 자연을 압축 체험할 수 있는 입문형 상품입니다.",
            ja: "短い日程でモンゴルの自然を楽しめる入門向け商品です。",
            en: "A short route ideal for first-time travelers wanting a compact Mongolia experience.",
        },
        tags: {
            ko: ["입문형", "가성비", "가족 추천"],
            ja: ["入門", "コスパ", "家族向け"],
            en: ["Starter", "Value", "Family"],
        },
        duration: { ko: "3박 4일", ja: "3泊4日", en: "3 nights 4 days" },
        highlights: {
            ko: ["테를지 국립공원", "초원 드라이브", "미니사막", "가벼운 일정"],
            ja: ["テレルジ国立公園", "草原ドライブ", "ミニ砂漠", "短期日程"],
            en: ["Terelj Park", "Steppe Drive", "Mini Desert", "Short Route"],
        },
    },
    {
        id: 3,
        region: "north",
        theme: "premium",
        durationType: "long",
        price: 2090000,
        deposit: 50000,
        gradient: "from-violet-700 to-indigo-400",
        heroImage: "/images/tour-lake-6n7d.jpg",
        images: ["/images/hero-khuvsgul.jpg", "/images/tour-lake-5n6d.jpg", "/images/tour-lake-7n8d.jpg"],
        detailImages: ["/images/detail-sample.jpg"],
        title: { ko: "홉스골 호수 6박 7일", ja: "フブスグル湖 6泊7日", en: "Khuvsgul Lake 6N7D" },
        desc: {
            ko: "북부 몽골의 고요한 호수와 숲 풍경을 중심으로 한 프리미엄 일정입니다.",
            ja: "北モンゴルの静かな湖と森を楽しむプレミアム日程です。",
            en: "A premium itinerary focused on northern Mongolia's lakes and forest landscapes.",
        },
        tags: {
            ko: ["프리미엄", "호수", "자연휴식"],
            ja: ["プレミアム", "湖", "自然"],
            en: ["Premium", "Lake", "Nature"],
        },
        duration: { ko: "6박 7일", ja: "6泊7日", en: "6 nights 7 days" },
        highlights: {
            ko: ["홉스골 호수", "북부 숲", "프리미엄 동선", "자연 휴식"],
            ja: ["フブスグル湖", "北部の森", "プレミアムルート", "自然休息"],
            en: ["Khuvsgul Lake", "Northern Forest", "Premium Route", "Nature Retreat"],
        },
    },
    // 남부 고비 사막 추가 투어
    {
        id: 4,
        region: "south",
        theme: "desert",
        durationType: "short",
        price: 1390000,
        deposit: 50000,
        gradient: "from-blue-600 to-blue-400",
        heroImage: "/images/tour-gobi-4n5d.jpg",
        images: ["/images/hero-gobi.jpg", "/images/tour-gobi-5n6d.jpg", "/images/tour-gobi-6n7d.jpg"],
        detailImages: ["/images/detail-sample.jpg"],
        title: { ko: "고비 사막 4박 5일", ja: "ゴビ砂漠 4泊5日", en: "Gobi Desert 4N5D" },
        desc: {
            ko: "사막과 협곡, 게르 숙박까지 고비의 핵심을 짧은 일정으로 압축한 상품입니다.",
            ja: "砂漠と渓谷、ゲル宿泊まで短い日程でゴビの魅力を凝縮したコースです。",
            en: "A condensed Gobi experience covering desert, canyon, and ger stay in a shorter schedule.",
        },
        tags: {
            ko: ["사막", "게르 숙박", "별보기"],
            ja: ["砂漠", "ゲル宿泊", "星空"],
            en: ["Desert", "Ger Stay", "Stargazing"],
        },
        duration: { ko: "4박 5일", ja: "4泊5日", en: "4 nights 5 days" },
        highlights: {
            ko: ["고비 사막", "게르 숙박", "별보기", "협곡 산책"],
            ja: ["ゴビ砂漠", "ゲル宿泊", "星空観察", "渓谷散策"],
            en: ["Gobi Desert", "Ger Stay", "Stargazing", "Canyon Walk"],
        },
    },
    {
        id: 5,
        region: "south",
        theme: "desert",
        durationType: "long",
        price: 1990000,
        deposit: 50000,
        gradient: "from-blue-600 to-blue-400",
        heroImage: "/images/tour-gobi-6n7d.jpg",
        images: ["/images/hero-gobi.jpg", "/images/tour-gobi-4n5d.jpg", "/images/tour-gobi-7n8d.jpg"],
        detailImages: ["/images/detail-sample.jpg"],
        title: { ko: "고비 사막 6박 7일", ja: "ゴビ砂漠 6泊7日", en: "Gobi Desert 6N7D" },
        desc: {
            ko: "사막의 다양한 지형을 여유 있게 탐험하는 심화 고비 코스입니다.",
            ja: "ゴビ砂漠の多様な地形をゆったり探検する上級コースです。",
            en: "An in-depth Gobi route exploring the desert's diverse terrain at a relaxed pace.",
        },
        tags: {
            ko: ["심화 코스", "낙타 투어", "게르"],
            ja: ["上級コース", "ラクダツアー", "ゲル"],
            en: ["In-depth", "Camel Tour", "Ger"],
        },
        duration: { ko: "6박 7일", ja: "6泊7日", en: "6 nights 7 days" },
        highlights: {
            ko: ["고비 사막", "낙타 투어", "모래언덕", "화석 지대"],
            ja: ["ゴビ砂漠", "ラクダツアー", "砂丘", "化石地帯"],
            en: ["Gobi Desert", "Camel Tour", "Sand Dunes", "Fossil Site"],
        },
    },
    {
        id: 6,
        region: "south",
        theme: "desert",
        durationType: "long",
        price: 2290000,
        deposit: 50000,
        gradient: "from-blue-600 to-blue-400",
        heroImage: "/images/tour-gobi-7n8d.jpg",
        images: ["/images/hero-gobi.jpg", "/images/tour-gobi-5n6d.jpg", "/images/tour-gobi-6n7d.jpg"],
        detailImages: ["/images/detail-sample.jpg"],
        title: { ko: "고비 사막 7박 8일", ja: "ゴビ砂漠 7泊8日", en: "Gobi Desert 7N8D" },
        desc: {
            ko: "고비의 끝에서 끝까지, 가장 완전한 고비 사막 탐험 코스입니다.",
            ja: "ゴビの端から端まで、最も完全なゴビ砂漠探検コースです。",
            en: "The most complete Gobi Desert expedition from end to end.",
        },
        tags: {
            ko: ["완전 탐험", "낙타", "화석"],
            ja: ["完全探検", "ラクダ", "化石"],
            en: ["Full Expedition", "Camel", "Fossils"],
        },
        duration: { ko: "7박 8일", ja: "7泊8日", en: "7 nights 8 days" },
        highlights: {
            ko: ["홍고린 모래언덕", "화석 지대", "낙타 트레킹", "고비 전 지형"],
            ja: ["ホンゴルイン砂丘", "化石地帯", "ラクダトレッキング", "ゴビ全地形"],
            en: ["Khongoryn Sand Dunes", "Fossil Sites", "Camel Trekking", "Full Gobi Terrain"],
        },
    },
    // 북부 호수 추가 투어
    {
        id: 7,
        region: "north",
        theme: "premium",
        durationType: "short",
        price: 1890000,
        deposit: 50000,
        gradient: "from-violet-700 to-indigo-400",
        heroImage: "/images/tour-lake-4n5d.jpg",
        images: ["/images/hero-khuvsgul.jpg", "/images/tour-lake-5n6d.jpg", "/images/tour-lake-6n7d.jpg"],
        detailImages: ["/images/detail-sample.jpg"],
        title: { ko: "북부 호수 4박 5일 항공", ja: "北部湖 4泊5日 航空", en: "North Lake 4N5D (Air)" },
        desc: {
            ko: "항공 이동으로 빠르게 북부 홉스골 호수를 경험하는 프리미엄 단기 코스입니다.",
            ja: "航空移動で素早く北部フブスグル湖を体験するプレミアム短期コースです。",
            en: "A premium short course reaching the northern Khuvsgul Lake quickly by air.",
        },
        tags: {
            ko: ["항공", "호수", "프리미엄"],
            ja: ["航空", "湖", "プレミアム"],
            en: ["Air", "Lake", "Premium"],
        },
        duration: { ko: "4박 5일", ja: "4泊5日", en: "4 nights 5 days" },
        highlights: {
            ko: ["홉스골 호수", "항공 이동", "숲 트레킹", "보트 투어"],
            ja: ["フブスグル湖", "航空移動", "森トレッキング", "ボートツアー"],
            en: ["Khuvsgul Lake", "Flight Transfer", "Forest Trek", "Boat Tour"],
        },
    },
    {
        id: 8,
        region: "north",
        theme: "premium",
        durationType: "long",
        price: 1790000,
        deposit: 50000,
        gradient: "from-violet-700 to-indigo-400",
        heroImage: "/images/tour-lake-5n6d.jpg",
        images: ["/images/hero-khuvsgul.jpg", "/images/tour-lake-4n5d.jpg", "/images/tour-lake-7n8d.jpg"],
        detailImages: ["/images/detail-sample.jpg"],
        title: { ko: "북부 호수 5박 6일", ja: "北部湖 5泊6日", en: "North Lake 5N6D" },
        desc: {
            ko: "홉스골 호수와 주변 숲을 여유롭게 즐기는 북부 기본 코스입니다.",
            ja: "フブスグル湖と周辺の森をゆっくり楽しむ北部基本コースです。",
            en: "The standard northern route enjoying Khuvsgul Lake and the surrounding forest.",
        },
        tags: {
            ko: ["호수", "자연", "승마"],
            ja: ["湖", "自然", "乗馬"],
            en: ["Lake", "Nature", "Horse Riding"],
        },
        duration: { ko: "5박 6일", ja: "5泊6日", en: "5 nights 6 days" },
        highlights: {
            ko: ["홉스골 호수", "숲 트레킹", "승마", "일몰 감상"],
            ja: ["フブスグル湖", "森トレッキング", "乗馬", "夕日観賞"],
            en: ["Khuvsgul Lake", "Forest Trek", "Horse Riding", "Sunset View"],
        },
    },
    {
        id: 9,
        region: "north",
        theme: "premium",
        durationType: "long",
        price: 2390000,
        deposit: 50000,
        gradient: "from-violet-700 to-indigo-400",
        heroImage: "/images/tour-lake-7n8d.jpg",
        images: ["/images/hero-khuvsgul.jpg", "/images/tour-lake-4n5d.jpg", "/images/tour-lake-5n6d.jpg"],
        detailImages: ["/images/detail-sample.jpg"],
        title: { ko: "북부 호수 7박 8일 기차 여행", ja: "北部湖 7泊8日 列車旅", en: "North Lake 7N8D (Train)" },
        desc: {
            ko: "울란바토르에서 기차로 출발해 북부 대자연을 여유롭게 탐험하는 특별한 여정입니다.",
            ja: "ウランバートルから列車で出発し、北部の大自然をゆっくり探検する特別な旅です。",
            en: "A special journey departing by train from Ulaanbaatar to explore northern Mongolia's vast nature.",
        },
        tags: {
            ko: ["기차 여행", "호수", "특별 코스"],
            ja: ["列車旅", "湖", "特別コース"],
            en: ["Train Journey", "Lake", "Special Route"],
        },
        duration: { ko: "7박 8일", ja: "7泊8日", en: "7 nights 8 days" },
        highlights: {
            ko: ["기차 탑승", "홉스골 호수", "북부 숲", "유목민 체험"],
            ja: ["列車乗車", "フブスグル湖", "北部の森", "遊牧民体験"],
            en: ["Train Ride", "Khuvsgul Lake", "Northern Forest", "Nomad Experience"],
        },
    },
    // 중부 초원 추가 투어
    {
        id: 10,
        region: "central",
        theme: "family",
        durationType: "short",
        price: 390000,
        deposit: 50000,
        gradient: "from-sky-900 to-blue-500",
        heroImage: "/images/tour-steppe-1n2d.jpg",
        images: ["/images/hero-terelj.jpg", "/images/tour-steppe-2n3d.jpg", "/images/tour-steppe-3n4d.jpg"],
        detailImages: ["/images/detail-sample.jpg"],
        title: { ko: "테를지 1박 2일", ja: "テレルジ 1泊2日", en: "Terelj 1N2D" },
        desc: {
            ko: "주말을 이용해 울란바토르 근교 테를지 국립공원을 가볍게 체험하는 입문 코스입니다.",
            ja: "週末を使ってウランバートル近郊のテレルジ国立公園を気軽に体験する入門コースです。",
            en: "A quick weekend getaway to Terelj National Park, just outside Ulaanbaatar.",
        },
        tags: {
            ko: ["입문", "당일 가능", "가성비"],
            ja: ["入門", "日帰り可", "コスパ"],
            en: ["Intro", "Day Trip", "Value"],
        },
        duration: { ko: "1박 2일", ja: "1泊2日", en: "1 night 2 days" },
        highlights: {
            ko: ["테를지 국립공원", "게르 숙박", "승마 체험", "초원 산책"],
            ja: ["テレルジ国立公園", "ゲル宿泊", "乗馬体験", "草原散策"],
            en: ["Terelj Park", "Ger Stay", "Horse Riding", "Steppe Walk"],
        },
    },
    {
        id: 11,
        region: "central",
        theme: "family",
        durationType: "short",
        price: 590000,
        deposit: 50000,
        gradient: "from-sky-900 to-blue-500",
        heroImage: "/images/tour-steppe-2n3d.jpg",
        images: ["/images/hero-terelj.jpg", "/images/tour-steppe-1n2d.jpg", "/images/tour-steppe-3n4d.jpg"],
        detailImages: ["/images/detail-sample.jpg"],
        title: { ko: "테를지 2박 3일", ja: "テレルジ 2泊3日", en: "Terelj 2N3D" },
        desc: {
            ko: "테를지 초원에서 2박을 머물며 몽골 자연과 유목 문화를 여유 있게 경험합니다.",
            ja: "テレルジ草原で2泊し、モンゴルの自然と遊牧文化をゆっくり体験します。",
            en: "Two nights in the Terelj steppe to enjoy Mongolia's nature and nomadic culture at a relaxed pace.",
        },
        tags: {
            ko: ["초원", "유목 문화", "가족"],
            ja: ["草原", "遊牧文化", "家族"],
            en: ["Steppe", "Nomad Culture", "Family"],
        },
        duration: { ko: "2박 3일", ja: "2泊3日", en: "2 nights 3 days" },
        highlights: {
            ko: ["테를지 초원", "게르 숙박", "유목 체험", "자연 산책"],
            ja: ["テレルジ草원", "ゲル宿泊", "遊牧体験", "自然散策"],
            en: ["Terelj Steppe", "Ger Stay", "Nomad Experience", "Nature Walk"],
        },
    },
    {
        id: 12,
        region: "central",
        theme: "family",
        durationType: "short",
        price: 1190000,
        deposit: 50000,
        gradient: "from-sky-900 to-blue-500",
        heroImage: "/images/tour-steppe-4n5d.jpg",
        images: ["/images/hero-terelj.jpg", "/images/tour-steppe-3n4d.jpg", "/images/tour-steppe-5n6d.jpg"],
        detailImages: ["/images/detail-sample.jpg"],
        title: { ko: "테를지 · 온천 · 미니사막 4박 5일", ja: "テレルジ・温泉・ミニ砂漠 4泊5日", en: "Terelj · Hot Spring · Mini Desert 4N5D" },
        desc: {
            ko: "테를지 초원, 천연 온천, 미니사막까지 중부 몽골의 다양한 자연을 담은 코스입니다.",
            ja: "テレルジ草原、天然温泉、ミニ砂漠まで中部モンゴルの多様な自然を詰め込んだコースです。",
            en: "A diverse route covering Terelj steppe, natural hot springs, and the mini desert of central Mongolia.",
        },
        tags: {
            ko: ["온천", "미니사막", "가족"],
            ja: ["温泉", "ミニ砂漠", "家族"],
            en: ["Hot Spring", "Mini Desert", "Family"],
        },
        duration: { ko: "4박 5일", ja: "4泊5日", en: "4 nights 5 days" },
        highlights: {
            ko: ["테를지 국립공원", "천연 온천", "미니사막", "초원 승마"],
            ja: ["テレルジ国立公園", "天然温泉", "ミニ砂漠", "草原乗馬"],
            en: ["Terelj Park", "Natural Hot Spring", "Mini Desert", "Steppe Riding"],
        },
    },
    {
        id: 13,
        region: "central",
        theme: "family",
        durationType: "long",
        price: 1490000,
        deposit: 50000,
        gradient: "from-sky-900 to-blue-500",
        heroImage: "/images/tour-steppe-5n6d.jpg",
        images: ["/images/hero-terelj.jpg", "/images/tour-steppe-3n4d.jpg", "/images/tour-steppe-4n5d.jpg"],
        detailImages: ["/images/detail-sample.jpg"],
        title: { ko: "어기 호수 · 테를지 5박 6일", ja: "オギ湖・テレルジ 5泊6日", en: "Ogii Lake · Terelj 5N6D" },
        desc: {
            ko: "어기 호수 철새와 테를지 초원, 온천, 미니사막, 폭포까지 중부 대표 코스입니다.",
            ja: "オギ湖の渡り鳥、テレルジ草原、温泉、ミニ砂漠、滝まで中部代表コースです。",
            en: "The signature central Mongolia route covering Ogii Lake birds, Terelj steppe, hot springs, mini desert, and waterfall.",
        },
        tags: {
            ko: ["어기 호수", "철새", "폭포"],
            ja: ["オギ湖", "渡り鳥", "滝"],
            en: ["Ogii Lake", "Migratory Birds", "Waterfall"],
        },
        duration: { ko: "5박 6일", ja: "5泊6日", en: "5 nights 6 days" },
        highlights: {
            ko: ["어기 호수", "테를지", "천연 온천", "미니사막", "폭포"],
            ja: ["オギ湖", "テレルジ", "天然温泉", "ミニ砂漠", "滝"],
            en: ["Ogii Lake", "Terelj", "Hot Spring", "Mini Desert", "Waterfall"],
        },
    },
    // 서부 알타이 투어
    {
        id: 14,
        region: "west",
        theme: "adventure",
        durationType: "long",
        price: 2490000,
        deposit: 50000,
        gradient: "from-amber-700 to-orange-500",
        heroImage: "/images/tour-altai-zavkhan.jpg",
        images: ["/images/hero-altai.jpg", "/images/tour-altai-air.jpg", "/images/tour-altai-12n13d.jpg"],
        detailImages: ["/images/detail-sample.jpg"],
        title: { ko: "자브항 7박 8일", ja: "ザブハン 7泊8日", en: "Zavkhan 7N8D" },
        desc: {
            ko: "서부 몽골 자브항 지역의 대자연과 유목 문화를 탐험하는 어드벤처 코스입니다.",
            ja: "西モンゴルのザブハン地域の大自然と遊牧文化を探検するアドベンチャーコースです。",
            en: "An adventure route exploring the vast nature and nomadic culture of the Zavkhan region in western Mongolia.",
        },
        tags: {
            ko: ["어드벤처", "자브항", "유목"],
            ja: ["アドベンチャー", "ザブハン", "遊牧"],
            en: ["Adventure", "Zavkhan", "Nomad"],
        },
        duration: { ko: "7박 8일", ja: "7泊8日", en: "7 nights 8 days" },
        highlights: {
            ko: ["자브항 강", "유목 캠프", "승마 트레킹", "서부 초원"],
            ja: ["ザブハン川", "遊牧キャンプ", "乗馬トレッキング", "西部草原"],
            en: ["Zavkhan River", "Nomad Camp", "Horse Trekking", "Western Steppe"],
        },
    },
    {
        id: 15,
        region: "west",
        theme: "adventure",
        durationType: "long",
        price: 3990000,
        deposit: 50000,
        gradient: "from-amber-700 to-orange-500",
        heroImage: "/images/tour-altai-12n13d.jpg",
        images: ["/images/hero-altai.jpg", "/images/tour-altai-zavkhan.jpg", "/images/tour-altai-air.jpg"],
        detailImages: ["/images/detail-sample.jpg"],
        title: { ko: "알타이 산맥 12박 13일", ja: "アルタイ山脈 12泊13日", en: "Altai Mountains 12N13D" },
        desc: {
            ko: "몽골 서부 알타이 산맥을 완전히 탐험하는 최장기 프리미엄 어드벤처 코스입니다.",
            ja: "モンゴル西部アルタイ山脈を完全に探検する最長期プレミアムアドベンチャーコースです。",
            en: "The longest premium adventure route fully exploring the Altai Mountains of western Mongolia.",
        },
        tags: {
            ko: ["최장기", "알타이", "독수리 사냥"],
            ja: ["最長期", "アルタイ", "鷹狩り"],
            en: ["Longest", "Altai", "Eagle Hunting"],
        },
        duration: { ko: "12박 13일", ja: "12泊13日", en: "12 nights 13 days" },
        highlights: {
            ko: ["알타이 산맥", "독수리 사냥 문화", "카자흐 유목민", "산악 트레킹"],
            ja: ["アルタイ山脈", "鷹狩り文化", "カザフ遊牧民", "山岳トレッキング"],
            en: ["Altai Mountains", "Eagle Hunting Culture", "Kazakh Nomads", "Mountain Trekking"],
        },
    },
    {
        id: 16,
        region: "west",
        theme: "adventure",
        durationType: "long",
        price: 2890000,
        deposit: 50000,
        gradient: "from-amber-700 to-orange-500",
        heroImage: "/images/tour-altai-air.jpg",
        images: ["/images/hero-altai.jpg", "/images/tour-altai-12n13d.jpg", "/images/tour-altai-zavkhan.jpg"],
        detailImages: ["/images/detail-sample.jpg"],
        title: { ko: "알타이 산맥 항공 7박 8일", ja: "アルタイ山脈 航空 7泊8日", en: "Altai Mountains 7N8D (Air)" },
        desc: {
            ko: "항공으로 빠르게 이동해 알타이 산맥의 핵심을 압축 탐험하는 코스입니다.",
            ja: "航空で素早く移動してアルタイ山脈の核心を凝縮探検するコースです。",
            en: "A condensed Altai Mountains expedition with fast air transfers to the key highlights.",
        },
        tags: {
            ko: ["항공", "알타이", "압축 탐험"],
            ja: ["航空", "アルタイ", "凝縮探検"],
            en: ["Air", "Altai", "Condensed"],
        },
        duration: { ko: "7박 8일", ja: "7泊8日", en: "7 nights 8 days" },
        highlights: {
            ko: ["알타이 산맥", "항공 이동", "독수리 문화", "카자흐 유목"],
            ja: ["アルタイ山脈", "航空移動", "鷹狩り文化", "カザフ遊牧"],
            en: ["Altai Mountains", "Air Transfer", "Eagle Culture", "Kazakh Nomads"],
        },
    },
] as Tour[]).map(normalizeCmsTourImages);
